version: '3.4'

services:
  anchorhousewebflask:
    container_name: anchorhouse_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --host 0.0.0.0 --port 8080"]
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_APP=anchorwebflask/app.py
